var annotated =
[
    [ "AIEasy", "class_a_i_easy.html", "class_a_i_easy" ],
    [ "AIEasyTest", "class_a_i_easy_test.html", "class_a_i_easy_test" ],
    [ "AIHard", "class_a_i_hard.html", "class_a_i_hard" ],
    [ "AIHardTest", "class_a_i_hard_test.html", "class_a_i_hard_test" ],
    [ "Animation", "class_animation.html", "class_animation" ],
    [ "BoardGame", "class_board_game.html", "class_board_game" ],
    [ "Clock", "class_clock.html", "class_clock" ],
    [ "Connect4Animation", "class_connect4_animation.html", "class_connect4_animation" ],
    [ "Connect4AnimationPane", "class_connect4_animation_pane.html", "class_connect4_animation_pane" ],
    [ "Connect4GUI", "class_connect4_g_u_i.html", "class_connect4_g_u_i" ],
    [ "Connect4GUITest", "class_connect4_g_u_i_test.html", "class_connect4_g_u_i_test" ],
    [ "ConnectFour", "class_connect_four.html", "class_connect_four" ],
    [ "ConnectFourTest", "class_connect_four_test.html", "class_connect_four_test" ],
    [ "GameController", "class_game_controller.html", "class_game_controller" ],
    [ "GameControllerTest", "class_game_controller_test.html", "class_game_controller_test" ],
    [ "GUI", "class_g_u_i.html", "class_g_u_i" ],
    [ "HumanPlayer", "class_human_player.html", "class_human_player" ],
    [ "HumanPlayerTestJUnit", "class_human_player_test_j_unit.html", "class_human_player_test_j_unit" ],
    [ "LoadManager", "class_load_manager.html", "class_load_manager" ],
    [ "Othello", "class_othello.html", "class_othello" ],
    [ "OthelloAnimation", "class_othello_animation.html", "class_othello_animation" ],
    [ "OthelloAnimationPane", "class_othello_animation_pane.html", "class_othello_animation_pane" ],
    [ "OthelloAnimationPoint", "class_othello_animation_point.html", "class_othello_animation_point" ],
    [ "OthelloAnimationPointTest", "class_othello_animation_point_test.html", "class_othello_animation_point_test" ],
    [ "OthelloAnimationTest", "class_othello_animation_test.html", "class_othello_animation_test" ],
    [ "OthelloGUI", "class_othello_g_u_i.html", "class_othello_g_u_i" ],
    [ "OthelloGUITest", "class_othello_g_u_i_test.html", "class_othello_g_u_i_test" ],
    [ "OthelloTest", "class_othello_test.html", "class_othello_test" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "SaveManager", "class_save_manager.html", "class_save_manager" ],
    [ "SelectGame", "class_select_game.html", "class_select_game" ],
    [ "SelectGameTest", "class_select_game_test.html", "class_select_game_test" ],
    [ "Selection", "class_selection.html", "class_selection" ],
    [ "SelectionTest", "class_selection_test.html", "class_selection_test" ]
];